### ISSUE TITLE
Orbital survey antennas constantly makes the experiment button flash when it shouldn't

### ISSUE THREAD

**Issue by hjk321** [Falki-git/OrbitalSurvey#26]
If you have a part that can run an orbital survey, the experiment button will always flash blue and say an experiment is "available" if your mapping is less than 100% for the current SOI.

- Including Kerbol, which isn't even a valid orbital survey target
- Even if you are at the wrong altitude or not even in a stable orbit
- If you click the experiment button, the game will say the experiment is "running" but nothing happens.

I think the current system of manually enabling the survey from part manager, then having percentage milestone generate science reports works just fine - the problem is that we need to find a way to make the vanilla experiment button ignore the orbital survey experiment.

**Comment by Falki-git** [comment]
Thanks for the report. This is a known issue.

Currently there isn't a way to have the button not flash AND at the same time to disallow players from manually triggering the experiment (when it's not ready) by pushing the button. In other words, if I stop the button from flashing, then players can manually trigger the experiment, even if mapping is at 0%.

Hopefully an update to the game will arrive that tackles this, or someone will find a different way to trigger experiments that bypasses this issue.

**Comment by Falki-git** [comment]
Fixed in https://github.com/Falki-git/OrbitalSurvey/pull/30
