### ISSUE TITLE
Mod UI freeze up

### ISSUE THREAD

**Issue by tdaniely** [Falki-git/OrbitalSurvey#31]
First, thanks, great job. Found this right when I started Duna and immediately fired 4 sat payload to map it and Ike, fun mission, and scans work well.

Adding a waypoint after scan complete causes all mod GUIs except the map to stop responding, this is also for other mods, and this persists until reloading the game.
Also can't delete waypoint because of this.

Mod ver 0.9.4
Game ver 0.2.1.0

**Comment by tdaniely** [comment]
Suddenly started working, not sure what changed, didn't update anything, maybe mod reset in menus.

**Comment by Falki-git** [comment]
If it happens again please see if you can determine what exact steps are needed to produce that as I haven't noticed this behavior again. Except that sometimes, on a rare occasion, interracting with textfield controls can cause the entire UI to lock up. But I couldn't reproduce that consistently.

**Comment by tdaniely** [comment]
I did get it one more time, it's something with right clicking an existing waypoint, I still don't know what the situation is, but when it happens, right clicking the waypoint, the remove button is missing, and then the ui gets stuck in unresponsive.
Feels like something around the PointerUp events. Maybe an edge click can trigger both map & marker events?
