### ISSUE TITLE
Scanning on Gilly

### ISSUE THREAD

**Issue by Fenris42** [Falki-git/OrbitalSurvey#9]
Unable to create region scan on Gilly because min altitude is above SOI max altitude

Visual scan is barely possible at max altitude allowed by SOI. Scan just creates the thinnest of lines and takes forever to be completed.

Suggest min/max altitude not being a hard limit and more of a guideline for best results while scanning to have more flexibility for situations like this

video of visual scanning at max altitude of Gillies SOI and at max fast forward

https://github.com/Falki-git/OrbitalSurvey/assets/133166853/006a1423-1b7a-4d77-ae48-8b765808c247

**Comment by Falki-git** [comment]
Yes, this is a known issue that will be addressed. I'm thinking of either dynamically calculating the altitudes depending on body's radius & SOI or having predefined presets for the size of the body, like "small bodies", "Kerbin-sized bodies", "gas giants". I'm leaning on the 2nd solution as it could be more easily communicated before launching a mission.

**Comment by Falki-git** [comment]
Solved in https://github.com/Falki-git/OrbitalSurvey/pull/15
